# JSON Precinct Variable names 
PRECINCT_ID = "id"
PRECINCT_NEIGHBORS_LIST = "neighbor"
PRECINCT_POPULATION = "population"

# file names
ARKANSAS_NEIGHBOR_FILENAME = "AR_Neighbor.json"
SOUTHCAROLINA_NEIGHBOR_FILENAME = "SC_Neighbor.json"
VIRGINIA_NEIGHBOR_FILENAME = "VA_Neighbor.json"

# district numbers 
ARKANSAS_NUM_DISTRICTS = 4
SOUTHCAROLINA_NUM_DISTRICTS = 7
VIRGINIA_NUM_DISTRICTS = 11

# state name constants 
ARKANSAS = "arkansas"
ARKANSAS_ABBREVIATION = "ak"
SOUTHCAROLINA = "south carolina"
SOUTHCAROLINA_ABBREVIATION = "sc"
VIRGINIA = "virginia"
VIRGINIA_ABBREVIATION = "va"